import { Voiture_utilitaire, voiture_U1, voiture_U2 } from "./class/type_voiture/voiture_utilitaire";
import { IVoiture, afficher } from "./class/type_voiture/Interface_voitures";
console.log(afficher.tableau_marque());
console.log();
console.log(afficher.tableau_modele());
console.log();
console.log(afficher.tableau_imatriculation());
console.log();
console.log(afficher.tableau_couleur());
console.log();
console.log(afficher.tableau_kilometre());
console.log();
console.log(afficher.tableau_prix());
console.log();
console.log(afficher.tableau_anne_cerculation());